version: "3.9"
services:
  db:
    container_name: rederly_db
    image: postgres:12.6
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "65432:5432"
      - "5432"

  backend:
    build: ../source/backend
    container_name: rederly_backend
    volumes:
      - type: bind
        source: ./configurations/backend.env
        target: /rederly/.env
      - type: bind
        source: ../source/backend/.sequelizerc
        target: /rederly/.sequelizerc
    depends_on:
      - db

  scheduler-redis:
    image: "redis:alpine"

  scheduler:
    build: ../source/scheduler
    depends_on:
      - scheduler-redis
    environment:
      REDIS_HOST: scheduler-redis

  library-browser-db:
    container_name: rederly_library-browser-db
    image: postgres:12.6
    volumes:
      - "librarydbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  library-browser:
    build: ../source/library-browser
    depends_on:
      - library-browser-db
    volumes:
      - type: bind
        source: ./configurations/library-browser.env
        target: /rederly/.env


  rederly-course-export:
    container_name: rederly_rederly-course-export
    build:
      context: ../source/rederly-course-export
      dockerfile: Dockerfile.standalone
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./configurations/rederly-course-export.env
        target: /rederly-course-export-standalone/.env
  

  bulk-pdf-export:
    build: '../source/bulk-pdf-export'
    cap_add: 
      - SYS_ADMIN
    volumes:
      - type: bind
        source: ./configurations/bulk-pdf-export.env
        target: /app/.env
  
  frontend-build:
    build:
      context: ../source/frontend
      dockerfile: build.Dockerfile

  proxy:
    build: ./nginx
    depends_on:
      - frontend-build
      - backend
      - library-browser
    ports:
      - "3000:80"
    container_name: rederly_proxy
    # This is for quicker debugging:
    # 1. Uncomment the rederly.nginx.conf volume
    # 2. Make changes to the file
    # 3. Reload nginx: `docker exec -it rederly_proxy nginx -s reload`
    # volumes:
    #   - type: bind
    #     source: ./nginx/rederly.nginx.conf
    #     target: /etc/nginx/conf.d/rederly.nginx.conf



volumes:
  dbdata:
  librarydbdata: